### PR TITLE
move samples to dbpack-samples

### PR DESCRIPTION
**Pull request by JuwanXu**
ref: https://github.com/cectc/dbpack/issues/62

### CODE REVIEW

**Comment by JuwanXu** [comment]
have read the CLA Document and I hereby sign the CLA

**Comment by JuwanXu** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by JuwanXu** [comment]
recheck

**Review by Lvnszn — APPROVED** [review]

**Review by dk-lockdown — APPROVED** [review]
LGTM

**Review by bohehe — APPROVED** [review]
LGTM

**Pull request merged**
