### PR TITLE
add unit test cases for `convertAssignRows`

### PR DESCRIPTION
**Pull request by dk-lockdown**
ref: https://github.com/cectc/dbpack/issues/<issueID>

### CODE REVIEW

**Comment by adofsauron** [comment]
LGTM

**Comment by gorexlv** [comment]
It looks more elegant if put private functions after public ones.  😺

**Comment by zackzhangkai** [comment]
LGTM

**Comment by dk-lockdown** [comment]
> It looks more elegant if put private functions after public ones. 😺

it's done

**Pull request merged**
