### PR TITLE
fix: in tcc mode, json.Unmarshal requestContext.Headers failed

### PR DESCRIPTION
**Pull request by dk-lockdown**
ref: 
https://github.com/CECTC/dbpack/issues/12
https://github.com/cectc/dbpack/issues/194

### Ⅰ. Describe what this PR did

1. `requestContext.Headers` unmarshal failed
2. Incorrect `host` passed in
3. Got wrong `QueryString`

### Ⅳ. Describe how to verify it
verified by [tcc sample](https://github.com/CECTC/dbpack-samples/pull/17)
image

image

### CODE REVIEW

**Comment by fatelei** [comment]
how to find this bug

**Comment by dk-lockdown** [comment]
> how to find this bug

When I develop the tcc sample and start debugging, the program does not run correctly, and was not submitted or rolled back as expected.

**Comment by fatelei** [comment]
> > how to find this bug
> 
> When I develop the tcc sample and start debugging, the program does not run correctly, and was not submitted or rolled back as expected.

your test script can be a unittest ?

**Comment by dk-lockdown** [comment]
> > > how to find this bug
> > 
> > 
> > When I develop the tcc sample and start debugging, the program does not run correctly, and was not submitted or rolled back as expected.
> 
> your test script can be a unittest ?

ok， i will add unit test for `RequestContext.Encode` and `RequestContext.Decode`

**Review by fatelei — APPROVED** [review]

**Review by bohehe — APPROVED** [review]
LGTM

**Pull request merged**
